---
# roles/microk8s/tasks/configure-cert-manager.yml
#
- name: configure cert-manager
  become: false
  run_once: "{{run_once}}"
  block:
    - name: jetstack helm chart
      kubernetes.core.helm_repository:
        binary_path: "{{helm}}"
        repo_name: jetstack
        repo_state: present
        repo_url: https://charts.jetstack.io
      delegate_to: "{{delegate_to}}"

    - name: cert-manager CRDs
      ansible.builtin.shell:
        cmd: >
          {{kubectl}} apply
          -f https://github.com/cert-manager/cert-manager/releases/download/{{microk8s_cert_manager_version}}/cert-manager.crds.yaml
      register: kubectl_apply_cert_manager_crds
      delegate_to: "{{delegate_to}}"
      changed_when: kubectl_apply_cert_manager_crds.stdout_lines |reject('search','unchanged') |list |length >0

    - name: cert-manager
      kubernetes.core.helm:
        binary_path: "{{helm}}"
        chart_ref: jetstack/cert-manager
        chart_version: "{{microk8s_cert_manager_version}}"
        create_namespace: true
        release_name: cert-manager
        release_namespace: cert-manager
        release_state: present
        release_values:
          ingressShim.defaultIssuerName: selfsign
          ingressShim.defaultIssuerKind: ClusterIssuer
          ingressShim.defaultIssuerGroup: cert-manager.io
        skip_crds: true
        update_repo_cache: false
        wait: true
      delegate_to: "{{delegate_to}}"

    - name: cert-manager issuer selfsign
      ansible.builtin.shell:
        cmd: |
          cat <<EOT |{{kubectl}} apply -f -
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: selfsigned
          spec:
            selfSigned: {}
          EOT
      register: kubectl_apply_selfsign
      delegate_to: "{{delegate_to}}"
      changed_when: kubectl_apply_selfsign.stdout_lines |reject('search','unchanged') |list |length >0

    - name: cert-manager root CA
      ansible.builtin.shell:
        cmd: |
          cat <<EOT |{{kubectl}} apply -f -
          ---
          apiVersion: cert-manager.io/v1
          kind: Certificate
          metadata:
            name: ca-issuer-root-x1
            namespace: cert-manager
          spec:
            isCA: true
            commonName: Microk8s Root X1
            duration: 175200h
            secretName: ca-issuer-root-x1
            privateKey:
              algorithm: ECDSA
              size: 256
            issuerRef:
              name: selfsigned
              kind: ClusterIssuer
              group: cert-manager.io
          ---
          apiVersion: cert-manager.io/v1
          kind: ClusterIssuer
          metadata:
            name: ca-issuer
          spec:
            ca:
              secretName: ca-issuer-root-x1
          EOT
      register: kubectl_apply_ca
      delegate_to: "{{delegate_to}}"
      changed_when: kubectl_apply_ca.stdout_lines |select('match','(created|updated)$') |list |length == 0
      #changed_when: kubectl_apply_ca.stdout_lines |reject('search','unchanged') |list |length >0
      when:
        - microk8s_cert_manager_rootCA_issuer
