- name: microk8s enable features
  ansible.builtin.command:
    cmd: /snap/bin/microk8s enable {{ item }}
  delegate_to: "{{ (ansible_local['microk8s']['high-availability']['nodes'] |length >1)
                   |ternary(primary_node,'') }}"
  run_once: "{{ ansible_local['microk8s']['high-availability']['nodes'] |length >1 }}"
  with_items:
    - "{{ microk8s_features }}"
  when:
    - (ansible_local.microk8s.addons |selectattr('name','contains', item.split(':')[0] ) |first).status == "disabled"
