---
# tasks file for microk8s
- name: install
  community.general.snap:
    channel: "{{ microk8s_snap_channel }}"
    classic: yes
    name: microk8s
    state: present
  register: microk8s_install

- name: group membership
  ansible.builtin.user:
    append: yes
    groups: microk8s
    name: "{{ item }}"
  with_items:
    - "{{ microk8s_group_members }}"

- name: KUBECONFIG kubectl setup
  ansible.builtin.copy:
    dest: /etc/profile.d/KUBECONFIG.sh
    src: files/KUBECONFIG.sh

- name: create ansible local facts directory
  ansible.builtin.file:
    path: /etc/ansible/facts.d
    state: directory

- name: install local facts script
  ansible.builtin.copy:
    dest: /etc/ansible/facts.d/microk8s.fact
    mode: 0755
    src: files/microk8s.fact
  register: microk8s_facts

- name: wait for microk8s to start
  ansible.builtin.command:
    cmd: /snap/bin/microk8s status --format yaml --wait-ready --timeout 60
  changed_when: false
  when: microk8s_install.changed

- name: reload ansible local facts
  ansible.builtin.setup:
    filter: ansible_local
  when: microk8s_facts.changed
