---
- name: microk8s add-node
  ansible.builtin.shell:
    cmd: /snap/bin/microk8s add-node
  changed_when: false
  delegate_to: "{{ primary_node }}"
  delay: "{{ 10 |random }}"
  register: microk8s_add_node

- name: join host to cluster
  ansible.builtin.command:
    cmd: "/snap/bin/{{ microk8s_add_node.stdout
             |regex_search('microk8s join ' + join_address + ':.*$', multiline=True)
             |string }}
          {{ is_worker |ternary(' --worker','') }}"

- name: reload ansible facts
  ansible.builtin.setup:
    filter: ansible_local

