---
# tasks file for microk8s
- name: install
  ansible.builtin.include_tasks: install.yml

- name: configure
  ansible.builtin.include_tasks: config.yml
  when:
    - groups[microk8s_cluster_group] is defined
    - inventory_hostname in groups[microk8s_cluster_group]
    - inventory_hostname == groups[microk8s_cluster_group] | first
    - ansible_local.microk8s is defined
    - ansible_local.microk8s.addons is defined

- name: join cluster
  ansible.builtin.include_tasks: join.yml
  when:
    - groups[microk8s_cluster_group] is defined
    - inventory_hostname in groups[microk8s_cluster_group]
    - inventory_hostname != groups[microk8s_cluster_group] | first
    - ansible_local.microk8s is defined
    - ansible_local['microk8s']['high-availability'] is defined
    - ansible_local['microk8s']['high-availability']['enabled'] == true
    - ansible_local['microk8s']['high-availability']['nodes'] | length <= 1
